### ISSUE TITLE
Please merge FORTIFY_SOURCE FAQ answers

### ISSUE THREAD

**Issue by sitsofe** [google/sanitizers#743]
The FAQ at the bottom of https://github.com/google/sanitizers/wiki/AddressSanitizer currently has two answers saying the following:

Q: Why didn't ASan report an obviously invalid memory access in my code?

A3: The fortify source compiler feature can mask errors that ASan is able to detect. On some systems (Ubuntu, Gentoo) fortify source is enabled by default, you can make sure it's disabled by passing -U_FORTIFY_SOURCE in your compiler flags.

Q: I've compiled my code with -D_FORTIFY_SOURCE flag and ASan, but I've got strange errors in runtime. What goes wrong?

A: Currently ASan (and other sanitizers) doesn't support source fortification, see https://github.com/google/sanitizers/issues/247

The link in the second answer would also apply to the first - could they somehow be merged or otherwise refer to each other? Further, doesn't this affect all sanitizers not just ASan?

**Comment by kcc** [comment]
On Wed, Nov 16, 2016 at 10:46 PM, Sitsofe Wheeler <notifications@github.com>
wrote:

> The FAQ at the bottom of https://github.com/google/sanitizers/wiki/
> AddressSanitizer currently has two answers saying the following:
>
> Q: Why didn't ASan report an obviously invalid memory access in my code?
>
> A3: The fortify source compiler feature can mask errors that ASan is able
> to detect. On some systems (Ubuntu, Gentoo) fortify source is enabled by
> default, you can make sure it's disabled by passing -U_FORTIFY_SOURCE in
> your compiler flags.
>
> Q: I've compiled my code with -D_FORTIFY_SOURCE flag and ASan, but I've
> got strange errors in runtime. What goes wrong?
>
> A: Currently ASan (and other sanitizers) doesn't support source
> fortification, see #247 <https://github.com/google/sanitizers/issues/247>
>
> The link in the second answer would also apply to the first - could they
> somehow be merged or otherwise refer to each other?
>

Done.


> Further, doesn't this affect all sanitizers not just ASan?
>
Yes.
Sadly, the discussion with glibc folks died out.

**Comment by kcc** [comment]
done.

Yes, this affectstsan & msan too. 
Sadly, the discussion with glibc folks died out.

**Comment by sitsofe** [comment]
Looks neater (one answer refers to the other) but it's probably good to keep the mention of the distros that enable it by default (previously it said Gentoo and Ubuntu) and how to disable it on them  (using `-U_FORTIFY_SOURCE`) because it took a while for me to twig it was fortify source causing the problem when I was using the sanitizers on Ubuntu.

**Comment by yugr** [comment]
> mention of the distros that enable it by default (previously it said Gentoo and Ubuntu)

Also Fedora and RedHat (https://people.redhat.com/sgrubb/files/hardening-elf-apps.pdf). Actually I think all modern distros enable it.

**Comment by kcc** [comment]
One of the problems is that -U_FORTIFY_SOURCE does not actually work in some cases since there are libraries pre-built with -D_FORTIFY_SOURCE

**Comment by sitsofe** [comment]
@morehouse It kind isn't quite fixed actually. See A3 and the bigger answer below on https://github.com/google/sanitizers/wiki/AddressSanitizer . Can you reopen this or amend the wiki?

**Comment by morehouse** [comment]
Moved the second Q/A right after the first one for clarity.

**Comment by ohhai** [comment]
> One of the problems is that -U_FORTIFY_SOURCE does not actually work in some cases since there are libraries pre-built with -D_FORTIFY_SOURCE

Does it mean that the only proper way to apply ASAN in modern Ubuntu/Fedora/... is to rebuild the app and  _all_  libraries it uses (including glibc, if used)?

Asking because of this: https://github.com/telegramdesktop/tdesktop/issues/17938
This is a bug with stack smashing in user app with fortifications enabled, and I see no significant result from adding `-fsanitize=address`. Am I doing something wrong?
